"""empty message

Revision ID: 6424080107ec
Revises: 8495ccc2fb68
Create Date: 2024-11-19 11:26:06.093166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6424080107ec'
down_revision = '8495ccc2fb68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'track', ['track_id'], ['track_id'])
        batch_op.alter_column('track_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    op.create_table('track',
    sa.Column('track_id', sa.INTEGER(), nullable=False),
    sa.Column('spotify_id', sa.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('track_id')
    )
    with op.batch_alter_table('track', schema=None) as batch_op:
        batch_op.create_index('ix_track_spotify_id', ['spotify_id'], unique=1)

    # ### end Alembic commands ###
